apiVersion: apps/v1
kind: Deployment
metadata:
  name: corpstore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corpstore
  template:
    metadata:
      labels:
        app: corpstore
    spec:
      securityContext:
        fsGroup: 1000
        runAsUser: 1000          # UID corpuser
      containers:
      - name: corpstore
        image: corpstore:db70d13
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /data
          name: data
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: corpstore-config
        - secretRef:
            name: corpstore-db-secret
        readinessProbe:
          httpGet:
            path: /ready
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /live
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
      volumes:
      - name: data
        emptyDir: {}